Ac 7
FusionIIIT/Fusion-mobile pull request #156
Opened 2024-03-10 11:08 UTC by jatin471

Unconflicted queries can directly be merged . In main conflicted queries pull request was made but they were genuine

2024-03-10 13:53 UTC, jatin471 commented
@prajjwalkapoor

2024-03-10 19:44 UTC, prajjwalkapoor commented
@Kushagra-Yadav 
@abhi87374⁰
@Kunal-2417

Do check if we can integrate this with the main.

2024-04-07 12:00 UTC, jatin471 commented
Added Verification Checkboxes and also wrote APIs for it and also resolved merge errors

2024-04-26 19:00 UTC, AgPriyanshu18 requested changes

2024-04-26 19:00 UTC, AgPriyanshu18 commented on ios/RunnerTests/RunnerTests.swift
> +class RunnerTests: XCTestCase {
This Folder should not be present

2024-04-26 19:00 UTC, AgPriyanshu18 commented
@jatin471 Please update distribution URL in gradle-wrapper-properties

2024-04-27 10:21 UTC, jatin471 commented on ios/RunnerTests/RunnerTests.swift
> +class RunnerTests: XCTestCase {
Removed

2024-04-27 11:04 UTC, AgPriyanshu18 approved these changes

2024-04-27 11:04 UTC, merged